services:
  backend:
    build:
      context: ./backend
    container_name: online-naplo-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:./dev.db"

  frontend:
    build:
      context: ./frontend
    container_name: online-naplo-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend